- type: entity
  parent: STBaseItem
  id: STCartridge
  abstract: true
  components:
  - type: CartridgeAmmo
    deleteOnSpawn: true
  - type: Appearance
  - type: SpentAmmoVisuals
    state: base
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-0.10,-0.05,0.10,0.05"
        density: 20
        mask:
        - ItemMask
        restitution: 0.3
        friction: 0.2
  - type: Damageable
    damageContainer: StructuralInorganic
    damageModifierSet: StrongMetallic
  - type: Destructible
    thresholds:
    - trigger:
        !type:DamageTrigger
        damage: 75
      behaviors:
      - !type:DoActsBehavior
        acts: [ "Destruction" ]
  - type: Tag
    tags:
    - Cartridge
  - type: EmitSoundOnLand
    sound:
      path: /Audio/Weapons/Guns/Casings/casing_fall_2.ogg
      params:
        volume: -1
