- type: entity
  id: StalkerRail
  name: рельсы #коммент чтобы сука заработало
  description: Старые ЖД пути, шпалы которых уже прогнили, а метал проржавел.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Appearance
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/rails.rsi
    drawdepth: FloorTiles
    layers:
      - state: rail
        scale: 0.6, 0.6
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: FootstepModifier
    footstepSoundCollection:
      collection: FootstepCatwalk
      params:
        volume: 8

# ВАГОНЫ С ЦИСТЕРНАМИ

- type: entity
  id: StalkerCargoTank
  parent: BaseStructure
  name: Вагон с цистерной
  description: Вид подвижного состава железных дорог для перевозки жидкостей, в том числе нефти и продуктов её переработки, химически активных и агрессивных жидких веществ.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo_tank
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoTank1
  parent: BaseStructure
  name: Вагон с цистерной
  description: Вид подвижного состава железных дорог для перевозки жидкостей, в том числе нефти и продуктов её переработки, химически активных и агрессивных жидких веществ.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo_tank1
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# ТЕПЛОВОЗЫ

- type: entity
  id: StalkerPassHead
  parent: BaseStructure
  name: Тепловоз М62
  description: Советский магистральный шестиосный тепловоз, изначально разработанный для эксплуатации в странах СЭВ. Выпускался Луганским тепловозостроительным заводом с 1965 года.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_head
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead
  parent: BaseStructure
  name: Тепловоз ТЭМ6-001
  description: Советский шестиосный маневровый тепловоз, производства Брянского завода. Создавался как универсальный локомотив, который после замены тележек или колёсных пар мог работать на железных дорогах с шириной колеи 1000, 1067, 1435 и 1520 мм, причём в условиях как умеренного, так и тропического климата.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: head_cargo
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead1
  parent: BaseStructure
  name: Тепловоз М62
  description: Советский магистральный шестиосный тепловоз, изначально разработанный для эксплуатации в странах СЭВ. Выпускался Луганским тепловозостроительным заводом с 1965 года.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo_head
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead2
  parent: BaseStructure
  name: Тепловоз ТЭМ6-001
  description: Советский шестиосный маневровый тепловоз, производства Брянского завода. Создавался как универсальный локомотив, который после замены тележек или колёсных пар мог работать на железных дорогах с шириной колеи 1000, 1067, 1435 и 1520 мм, причём в условиях как умеренного, так и тропического климата.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo_head2
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# ПАССАЖИРСКИЕ ВАГОНЫ

- type: entity
  id: StalkerPassTrain
  parent: BaseStructure
  name: пассажирский вагон
  description: Единица подвижного состава, предназначенная для перевозки пассажиров.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerPassTrain1
  parent: BaseStructure
  name: пассажирский вагон
  description: Единица подвижного состава, предназначенная для перевозки пассажиров.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train1
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerPassTrain2
  parent: BaseStructure
  name: пассажирский вагон
  description: Единица подвижного состава, предназначенная для перевозки пассажиров.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train3
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# ГРУЗОВЫЕ ВАГОНЫ

- type: entity
  id: StalkerCargo
  parent: BaseStructure
  name: грузовой вагон
  description: Представляет собой железнодорожное транспортное средство без двигателя, которое использовалось для перевозки грузов.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo1
  parent: BaseStructure
  name: грузовой вагон
  description: Представляет собой железнодорожное транспортное средство без двигателя, которое использовалось для перевозки грузов.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo1
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo2
  parent: BaseStructure
  name: грузовой вагон
  description: Представляет собой железнодорожное транспортное средство без двигателя, которое использовалось для перевозки грузов.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo2
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo3
  parent: BaseStructure
  name: грузовой вагон
  description: Представляет собой железнодорожное транспортное средство без двигателя, которое использовалось для перевозки грузов.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo3
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo4
  parent: BaseStructure
  name: грузовой вагон
  description: Представляет собой железнодорожное транспортное средство без двигателя, которое использовалось для перевозки грузов.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo4
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo5
  parent: BaseStructure
  name: грузовой вагон
  description: Представляет собой железнодорожное транспортное средство без двигателя, которое использовалось для перевозки грузов.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo5
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo6
  parent: BaseStructure
  name: грузовой вагон
  description: Представляет собой железнодорожное транспортное средство без двигателя, которое использовалось для перевозки грузов.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo6
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo7
  parent: BaseStructure
  name: грузовой вагон
  description: Представляет собой железнодорожное транспортное средство без двигателя, которое использовалось для перевозки грузов.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: сargo7
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

