- type: entity
  id: STAcidicEffect
  categories: [ HideSpawnMenu ]
  components:
  - type: TimedDespawn
    lifetime: 0.4
  - type: Sprite
    noRot: true
    drawdepth: Effects
    sprite: _Stalker/Effects/smoke.rsi
    scale: 0.5, 0.5
    state: smoke
    color: "#b0bf1a"
  - type: EffectVisuals
  - type: Tag
    tags:
      - HideContextMenu
  - type: AnimationPlayer
