- type: entity
  id: MobCharacteristics
  save: false
  abstract: true
  components:
    - type: CharacteristicContainer
    # Speed
    - type: CharacteristicModifierMovementSpeed
      maxBonus: 2
      minBonus: 0.1
      positiveModifier: 0.005
      negativeModifier: -0.005
    # Stamina
    - type: CharacteristicModifierStaminaCritThreshold
      minModifier: 0.1
      maxModifier: 1.5
      modifier: 0.01
    - type: CharacteristicModifierStaminaDecay
      minModifier: 0.1
      maxModifier: 2
      modifier: 0.01
    # Weight
    - type: CharacteristicModifierWeightMaximum
      minModifier: 0.1
      maxModifier: 3
      modifier: 0.01
- type: entity
  id: MobStaminaDamageable
  save: false
  abstract: true
  components:
    - type: Stamina
    - type: StaminaDecayModifier
    - type: StaminaCritThresholdModifier

- type: entity
  id: MobWeight
  save: false
  abstract: true
  components:
    - type: STWeight
    - type: STWeightMaximumModifier

- type: entity
  parent: EntityAnomalyTarget
  id: MobAnomalyTarget
  save: false
  abstract: true

- type: entity
  id: MobLay
  save: false
  abstract: true
  components:
    - type: STLay
