- type: entity
  id: STBaseMonument
  name: monument
  description: ancient structure of unknown origin
  suffix: ST, Mapping
  abstract: true
  components:
    - type: SpriteFade
    - type: Clickable
    - type: Sprite
      noRot: true
      sprite: _Stalker/Structures/Monuments/creators.rsi
      state: jerryimmouse
      drawdepth: Overdoors
    - type: Physics
      bodyType: Static
    - type: Fixtures
      fixtures:
        fix1:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.4,-0.5,0.4,-1.0"
          density: 1000
          layer:
            - WallLayer
