[game]
hostname = "☢️ S.T.A.L.K.E.R. Tools."
lobbyenabled = false
desc = "Server at S.T.A.L.K.E.R. setting.\nIn devlopment."
map = "STDev" # st-changes-dev-map
map_pool = "STDefaultMapPool"  # st-changes-map-pool
map_rotation = false

maxplayers = 80
soft_max_players = 60

role_timers = true
peaceful_end = false
contraband_examine = false

[server]
default_guide = "STNewPlayer"
rules_file = "STRuleset"

[rules]
time = 10.0

[whitelist]
enabled = false

[shuttle]
auto_call_time = 0
emergency = false
arrivals = false
preload_grids = false
camera_rotation_locked = true

[ic]
flavor_text = true
punctuation = false

[tts]
enabled = false

[infolinks]
discord = "https://discord.gg/pu6DEPGjsN"
patreon = "https://boosty.to/stalkerss14"

[hub]
advertise = false
tags = "lang:ru,lang:en,rp:medium,region:eu_e"

[events]
# Annoying
enabled = false

[openrouter]
# Almost zero credits avaiable on this
apikey = "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"
model = "openai/gpt-4.1"
url = "https://openrouter.ai/api/v1"