- type: entity
  id: STBaseTeleport
  abstract: true
  suffix: Teleport, Portal
  components:
    - type: Marker
    - type: Transform
      anchored: True
    - type: Physics
      bodyType: Static
    - type: Fixtures
      fixtures:
        portalFixture:
          shape:
            !type:PhysShapeAabb
            bounds: "-0.5,-0.5,0.5,0.5"
          mask:
            - FullTileMask
          layer:
            - TableLayer
          hard: false
    - type: InteractionOutline
    - type: Clickable
    - type: STAnomalyGeneratorSpawnBlocker
      size: 5

- type: entity
  parent: STBaseTeleport
  id: MapTeleportBase
  abstract: true
  components:
    - type: Sprite # I think you'll need to add an invisibility here
      layers:
        - state: portal-red
      sprite: /Textures/Effects/portal.rsi
    - type: NewMapTeleport
    - type: PointLight
      color: Yellow
      radius: 3
      energy: 1
      netsync: false

- type: entity
  parent: STBaseTeleport
  id: MapTeleportBaseUncollide
  abstract: true
  components:
    - type: Sprite # I think you'll need to add an invisibility here
      layers:
        - state: portal-red
      sprite: /Textures/Effects/portal.rsi
    - type: NewMapTeleport
      isCollisionDisabled: true
    - type: PointLight
      color: OrangeRed
      radius: 3
      energy: 1
      netsync: false

- type: entity
  parent: STBaseTeleport
  id: LocalTeleportBase
  abstract: true
  components:
    - type: Sprite # I think you'll need to add an invisibility here
      layers:
        - state: portal-red
      sprite: /Textures/Effects/portal.rsi
    - type: LocalTeleport

- type: entity
  parent: STBaseTeleport
  id: LocalTeleportBaseUncollide
  abstract: true
  components:
    - type: Sprite # I think you'll need to add an invisibility here
      layers:
        - state: portal-red
      sprite: /Textures/Effects/portal.rsi
    - type: LocalTeleport
# Portal system template

# Do not forget to add the same portal on your other location.
- type: entity
  parent:
    - STBaseTeleport
    - MapTeleportBase
  id: TemplateTeleport
  abstract: true
  name: TestMapTeleport
  components:
    - type: NewMapTeleport
      portalName: Test1
