- type: entity
  id: StandardStalkerStation # it was StandardNanotrasenStation previously
  parent:
    - BaseStation
    - BaseStationNews
    - BaseStationCargo
    - BaseStationJobsSpawning
    - BaseStationRecords
    # - BaseStationArrivals
    # - BaseStationGateway
    # - BaseStationShuttles
    # - BaseStationCentcomm
    # - BaseStationEvacuation
    # - BaseStationAlertLevels
    # - BaseStationMagnet
    # - BaseStationExpeditions
    # - BaseStationSiliconLawCrewsimov
    # - BaseStationAllEventsEligible
    # - BaseStationNanotrasen
  categories: [ HideSpawnMenu ]
  components:
    - type: Transform

