- type: job
  id: StalkerProjectPawn
  name: job-project-pawn
  icon: project-2
  description: job-project-pawn-desc
  playTimeTracker: JobProjectPawn
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobProjectPawn
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: ProjectPawnGear
  supervisors: job-project-pawn-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - ProjectPawn
            - Project
            - Stalker
        - type: Bands
          band: Stalker
          altBand: project-1
          canChange: true
          bandIcon: project-2
          bandProto: STProjectBand
          bandRankId: 2
        - type: IdentityBlocker
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: startingGear
  id: ProjectPawnGear
  equipment:
    id: ProjectPDA
    belt: ClothingBeltHolsterProject
    torso: ClothingTorsoJacketProjectPeshka
    legs: ClothingLegsJeansProjectPeshka
    shoes: ClothingShoesBootsProject
    ears: ClothingHeadsetProject
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesFingerless

- type: job
  id: StalkerProjectOrchestrator
  name: job-project-orchestrator
  icon: project-4
  description: job-project-orchestrator-desc
  playTimeTracker: JobProjectOrchestrator
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobProjectOrchestrator
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: ProjectOrchestratorGear
  supervisors: job-project-orchestrator-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Psyonics
        - type: PsyonicsActionSmoke
        - type: PsyonicsActionGrab
        - type: PsyonicsActionRift
        - type: Access
          tags:
            - ProjectPawn
            - ProjectOrchestrator
            - Project
            - Stalker
        - type: Bands
          band: Stalker
          altBand: project-3
          canChange: true
          bandIcon: project-4
          bandProto: STProjectBand
          bandRankId: 2
        - type: BlockTackingHolyItems
        - type: IdentityBlocker
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3
        - type: NpcFactionMember
          factions:
            - Mutated

- type: startingGear
  id: ProjectOrchestratorGear
  equipment:
    id: ProjectPDA
    belt: ClothingBeltHolsterProject
    torso: ClothingTorsoJacketProjectLeader
    legs: ClothingLegsJeansProjectLeader
    shoes: ClothingShoesBootsProject
    ears: ClothingHeadsetProject
    eyes: ClothingEyesHudProject
    gloves: ClothingHandsGlovesFingerless
- type: stBand
  id: STProjectBand
  name: Project
  factionId: Project
  maxMembers: 10
  managingRankId: 2
  hierarchy:
    1: StalkerProjectPawn
    2: StalkerProjectOrchestrator

