- type: entity
  parent: STBaseItem
  id: STBaseWeaponModule
  name: shit module
  description: A cleverly fucked-up contraption to create a wunderwaffle.
  abstract: true
  components:
    # I love you prototypers, to keep you out of the code,
    # all the parameters you can change are described here. 
    #
    # If something doesn't work,
    # this information is probably out of date, ask for an update
    - type: STWeaponModule
    #  effect:
    #    fireRateModifier: 1
    #    angleDecayModifier: 1
    #    angleIncreaseModifier: 1
    #    maxAngleModifier: 1
    #    minAngleModifier: 1
    #    projectileSpeedModifier: 1
    #    soundGunshotVolumeAddition: 0
    - type: Sprite
      state: icon
    - type: RepositoryItem
      categoryName: Оружие
      